export { HeroSection } from "./hero-section"
export { StatsSection } from "./stats-section"
export { ProgramOffersSection } from "./program-offers-section"
export { EventsSection } from "./events-section"
export { ProjectsSection } from "./projects-section"
export { GallerySection } from "./gallery-section"
